name: Security Scan
on: [pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Run make image (with cache)
        run: |
          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            -t transformer:latest .
          docker tag transformer:latest ghcr.io/nodyhub/transformer:latest
      
      - name: Run security scan
        uses: nodyhub/transformer@v0.0.1
        with:
          scan-file: '.github/transformer/scan.yml'
          fail-on-error: 'true'
