name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    
    - name: Run tests
      run: make test
    
    - name: Check go mod tidy
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum
        if [ $? -ne 0 ]; then
          echo "go.mod or go.sum is not tidy. Please run 'go mod tidy' and commit the changes."
          exit 1
        fi
